version: "3"
services:
  node:
    image: "node:8"
    user: "node"
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=production
    ports:
      - "4000:4000"
    volumes:
      - ./:/usr/src/app
    expose:
      - "4000"
    command: "npm start"